### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED :4004/api/sign-out:1   

### ISSUE THREAD

**Issue by Fan-Karwanta** [aelassas/movinin#3]
I did what the documentations stated, but when I am in the running from source code part, I got an issue about the axios, please help me I am few hours stucked in this problem :( 

![image](https://github.com/user-attachments/assets/50581e18-f743-4279-acb0-9a472461b91b)

**Comment by aelassas** [comment]
Can you check api logs? They are written in `./api/logs/all.log`

Also, make sure that the api is running by checking from your browser http://localhost:4004/api/locations/1/30/en

It should return a list of locations.

**Comment by Fan-Karwanta** [comment]
> Can you check api logs? They are written in `./api/logs/all.log`
> 
> Also, make sure that the api is running by checking from your browser http://localhost:4004/api/locations/1/30/en
> 
> It should return a list of locations.

Hello sir @aelassas I think my API is not running well, I dont know how but I already setted up my IIS, when I try to check the browser http://localhost:4004/api/locations/1/30/en it doesnt return any locations at all, I used mongoDB atlas, perhaps are you free for a quick google meet consultation sir, you will save my life since this is my capstone project.

**Comment by aelassas** [comment]
When you run the api with the following command:
```
cd ./api
npm run dev
```
What do you get in the command line output?

**Comment by Fan-Karwanta** [comment]
@aelassas I have these errors sir:

![image](https://github.com/user-attachments/assets/4af44fb4-6bef-44d8-b3fe-25c03fbee037)

![image](https://github.com/user-attachments/assets/3850f4a3-7d6e-4449-82d0-2a7c8e5a1e49)

**Comment by Fan-Karwanta** [comment]
Ohh nevermind sir I solved it :) . Thank you so much for your time :)

**Comment by aelassas** [comment]
Is the port 4004 already used by another process?

Stop the api, open powershell as admin and run `netstat -na | Select-String "4004"`

If you found an entry, this means that the port is already used by another process. So, you need to change the port of the api in api/.env, backend/.env and frontend/.env.

If you didn't find an entry:

1. Open powershell as admin
2. Run `net stop winnat`
3. Run `net start winnat`

If you didn't find an entry and still doesn't work, open powershell as admin, go to api folder and run `npm run dev`

If you didn't find an entry and still doesn't work, reboot and try again.

**Comment by Fan-Karwanta** [comment]
@aelassas I finally GOT IT!!! Thank you sooo much sir !!! May God Bless you <3

**Comment by aelassas** [comment]
You're welcome.
