### ISSUE TITLE
DATA NOT FETCHING from MONGODB ATLAS Database to Mobile app.

### ISSUE THREAD

**Issue by Fan-Karwanta** [aelassas/movinin#4]
I already disalbed Public network to my firewall. Already set up my .env file on my moblie/.env but when I try to search for properties and also if I try to log in I got error everytime. 

Perhaps do I need to deploy my database on docker? I preferably want not to deploy it on docker and since I am using MONGO DB Atlas I am expecting that my mobile app can fetch the data at ease, but its not. I think I just did something wrong with the localhost/127.0.0.1:4004 cause I think this is a double hostname or IP. I'm not sure though.

![image](https://github.com/user-attachments/assets/d4bf6cca-72a0-447a-b60b-254dd525eb96)

**Comment by aelassas** [comment]
In ./mobile/.env replace `localhost` by your local IP address:
1. Open powershell
2. Run `ipconfig`

Your local IP should be something like 192.168.1.108.

**Comment by Fan-Karwanta** [comment]
I did your suggestion sir sadly ites still the same, it doesnt fetch and sends the same errors. @aelassas

**Comment by aelassas** [comment]
It still tries to connect to localhost. The mobile app should point to a local IP not localhost and not 127.0.0.1. Replace all localhost occurences in mobile/.env by your local IP and run a clean start of the mobile app with `npm run start:clean`. You can get the local ip with `ipconfig` command.

**Comment by Fan-Karwanta** [comment]
still not working sir, perhaps do we need to be connected the both devices in a SAME WIFI network? or is it good even though we are not, the screenshot below is the IP config: @aelassas 

![image](https://github.com/user-attachments/assets/48c246ca-c17b-41ee-a964-7abf803ef3c2)

**Comment by Fan-Karwanta** [comment]
It's fine now sir :) thank you so much. I just need to apply the port 10.0.1.105 cause its the same network that we are connected with the mobile device. Thanks :) I already did this multiple times earlier, but my mistake is I didnt start clean with npm run start:clean

**Comment by Fan-Karwanta** [comment]
The author and owner of this repo is the best, so accomodating and fast to response :) Godbless people like him
