### ISSUE TITLE
CHECKOUT PAGE (WEB APP) Error / White Screen

### ISSUE THREAD

**Issue by Fan-Karwanta** [aelassas/movinin#5]
![image](https://github.com/user-attachments/assets/74cad7ea-023b-43dc-9814-80cece937e20)

When I search a property in the web app and click "BOOK NOW" button, supposedly it will redirect me to a checkout page. BUT it will redirect me to a checkout page that is blank. I dont know which error it is.

 I tried changing the frontend/.env file of the "VITE_BC_STRIPE_PUBLISHABLE_KEY"  (which is IN THE DOCUMENTATION) to "VITE_MI_STRIPE_PUBLISHABLE_KEY" (which is in the frontend/env.config.ts) and vice versa, stil got the same error. I cannot proceed to the checkout page of the WEB APP (only, cause my mobile app's checkout page is good).

**Comment by aelassas** [comment]
Can you try again with the latest version on main branch.

Add the following environment variable to frontend/.env:
```
VITE_MI_BASE_CURRENCY=USD
```

Remove the following environment variables from  frontend/.env:
```
VITE_MI_STRIPE_CURRENCY_CODE=USD
VITE_MI_CURRENCY=$
```

Then run the following commands:
```
cd path/to/movinin
git pull
cd frontend
npm i --force
npm run dev
```

For `VITE_MI_STRIPE_PUBLISHABLE_KEY` environment variable, it's `VITE_MI_STRIPE_PUBLISHABLE_KEY` and not `VITE_BC_STRIPE_PUBLISHABLE_KEY`:
```
VITE_MI_STRIPE_PUBLISHABLE_KEY=pk_test_XXXXXX
```

If you want to enable reCAPTCHA, set the following variables:
```
VITE_MI_RECAPTCHA_ENABLED=true
VITE_MI_RECAPTCHA_SITE_KEY=XXXXXXXXXXXXXXXXXXXXX
```

And add `localhost` to authorized domains in Google [reCAPTCHA console v3](https://www.google.com/recaptcha/admin).

**Comment by Fan-Karwanta** [comment]
Thank you so much! To be honest I didn't get the latest code in main branch. Well I did, and it doesnt fetch the properties that I have so I just went back to the previous front end code which is the Dec 26ish one and somewhat imitate the concept you did here in this issue and fix it.

Thank you so much again! You're the best!

**Comment by aelassas** [comment]
> To be honest I didn't get the latest code in main branch. Well I did, and it doesnt fetch the properties that I have so I just went back to the previous front end code

I have just fixed some issues in dev scripts of the main branch. So it should work now.

Try again with the latest version of the main branch:
```
cd path/to/dev/folder
git clone https://github.com/aelassas/movinin.git movinin-main
cd ./movinin-main/api
npm i
cd ./movinin-main/backend
npm i --force
cd ./movinin-main/frontend
npm i --force
```
* Copy your api/.env to ./movinin-main/api/.env
* Copy your backend/.env to ./movinin-main/backend/.env
* Copy your frontend/.env to ./movinin-main/frontend/.env

Add the following environment variable to frontend/.env:
```
VITE_MI_BASE_CURRENCY=USD
```

Remove the following environment variables from  frontend/.env:
```
VITE_MI_STRIPE_CURRENCY_CODE=USD
VITE_MI_CURRENCY=$
```

Run the api:
```
cd ./movinin-main/api
npm run dev
```

Run the backend:
```
cd ./movinin-main/backend
npm run dev
```

Run the frontend:
```
cd ./movinin-main/frontend
npm run dev
```
